# This configuration is intended for development purpose, it's **your** responsibility to harden it for production
name: delivery
services:
  app:
    image: delivery
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,api-docs
      - MANAGEMENT_PROMETHEUS_METRICS_EXPORT_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:mariadb://mariadb:3306/delivery?useLegacyDatetimeCode=false
      - SPRING_LIQUIBASE_URL=jdbc:mariadb://mariadb:3306/delivery?useLegacyDatetimeCode=false
    ports:
      - 127.0.0.1:8080:8080
    healthcheck:
      test:
        - CMD
        - curl
        - -f
        - http://localhost:8080/management/health
      interval: 5s
      timeout: 5s
      retries: 40
    depends_on:
      mariadb:
        condition: service_healthy
  mariadb:
    extends:
      file: ./mariadb.yml
      service: mariadb
