# DB template.
#
# This defines all the configurable parameters and other objects that are needed to run the PostgresDB service. This template can even be
# saved in OpenShift namespace as well so that have the flexibility to do any project specific customizations. Pls note wherever
# displayName says *** PLEASE DO NOT CHANGE THIS ***, don't touch that as those parameters will be referenced in other places.
#
apiVersion: v1
kind: Template
metadata:
  name: delivery-postgresqldb-template
  namespace: maximilianopizarro5-dev
  annotations:
    description: This template defines objects that are required to spin up a postgresqldb pod
    tags: db, delivery-postgresqldb  ,ephemeral
    openshift.io/display-name: delivery-postgresqldb-template
    openshift.io/long-description: >-
      This template provides objects that are required to spin up a postgresqldb pod.
      The database is not stored on persistent storage, so any restart of the service will result in all data being lost.
    openshift.io/provider-display-name: JHipster-OpenShift
labels:
  app: delivery-postgresqldb
  createdBy: JHipster-Team
parameters:
  - name: APPLICATION_NAME
    value: delivery-postgresqldb
    description: Name of the application
    required: true
    displayName: Application Name
  - name: SECRET_REF
    value: delivery-ds-secret-ref
    description: Name of the secret reference
    required: true
    displayName: "*** PLEASE DO NOT CHANGE THIS ***"
  - name: POSTGRESQL_USER
    displayName: PostgreSQL Connection Username
    description: Username for PostgreSQL user that will be used for accessing the database.
    value: delivery
    required: true
  - name: POSTGRESQL_PASSWORD
    displayName: PostgreSQL Connection Password
    description: Password for the PostgreSQL connection user.
    generate: expression
    from: "[a-zA-Z0-9]{16}"
    required: true
  - name: DATABASE_NAME
    displayName: PostgreSQL Database Name
    description: Name of the PostgreSQL database accessed.
    value: delivery
    required: true
  - name: SVC_ID
    value: jhipster
    description: Name of the service account
    required: true
    displayName: "*** PLEASE DO NOT CHANGE THIS ***"
  - name: VOLUME_CAPACITY
    displayName: Volume Capacity
    description: Volume space available for data, e.g. 512Mi, 2Gi.
    value: 1Gi
    required: true
objects:
  - apiVersion: v1
    kind: Secret
    metadata:
      name: ${SECRET_REF}
    stringData:
      database-user: "${POSTGRESQL_USER}"
      database-password: "${POSTGRESQL_PASSWORD}"
  - apiVersion: v1
    kind: DeploymentConfig
    metadata:
      name: ${APPLICATION_NAME}
      labels:
        app: ${APPLICATION_NAME}
    spec:
      # This is to define the deployment strategy (either be Rolling or Recreate)
      #     strategy:
      #       type: Rolling
      #       rollingParams:
      #         updatePeriodSeconds: 1
      #         intervalSeconds: 1
      #         timeoutSeconds: 600
      #         maxUnavailable: 25%
      #         maxSurge: 25%
      #       resources:
      triggers:
        - type: ConfigChange
      replicas: 1
      selector:
        app: ${APPLICATION_NAME}
      template:
        metadata:
          labels:
            app: ${APPLICATION_NAME}
        spec:
          volumes:
            - name: ${APPLICATION_NAME}-data
              emptyDir: {}
          containers:
            - name: ${APPLICATION_NAME}
              image: postgres:13.3
              env:
                - name: POSTGRES_DATABASE
                  value: ${DATABASE_NAME}
                  # This image requires the username to be db name
                - name: POSTGRES_USER
                  valueFrom:
                    secretKeyRef:
                      name: ${SECRET_REF}
                      key: database-user
                - name: POSTGRES_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: ${SECRET_REF}
                      key: database-password
              ports:
                - containerPort: 5432
                  protocol: TCP
              readinessProbe:
                timeoutSeconds: 1
                initialDelaySeconds: 15
                exec:
                  command:
                    - "/bin/sh"
                    - "-i"
                    - "-c"
                    - psql -h 127.0.0.1 -U $POSTGRES_USER -q -d $POSTGRES_DATABASE -c
                      'SELECT 1'
              livenessProbe:
                timeoutSeconds: 1
                initialDelaySeconds: 30
                tcpSocket:
                  port: 5432
              volumeMounts:
                - name: ${APPLICATION_NAME}-data
                  mountPath: /var/lib/postgresql/data
              resources:
              imagePullPolicy: IfNotPresent
          serviceAccount: ${SVC_ID}
          serviceAccountName: ${SVC_ID}
          restartPolicy: Always
          terminationGracePeriodSeconds: 30
  - apiVersion: v1
    kind: Service
    metadata:
      name: ${APPLICATION_NAME}
      labels:
        app: ${APPLICATION_NAME}
    spec:
      ports:
        - name: postgresqldb-bc
          protocol: TCP
          port: 5432
          targetPort: 5432
        - name: postgresqldb
          protocol: TCP
          port: 80
          targetPort: 5432
      selector:
        app: ${APPLICATION_NAME}
