kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: jhipster-devspace
spec:
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: 'delivery:latest'
  resources: {}
  successfulBuildsHistoryLimit: 5
  failedBuildsHistoryLimit: 5
  strategy:
    type: Source
    sourceStrategy:
      from:
        kind: DockerImage
        name: >-
          image-registry.openshift-image-registry.svc:5000/openshift/ubi8-openjdk-17:1.12
      incremental: true
  postCommit: {}
  source:
    type: Binary
    binary: {}
  runPolicy: Serial